/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanitiaRouteImport } from './routes/panitia'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DesainRouteImport } from './routes/desain'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PanitiaRoute = PanitiaRouteImport.update({
  id: '/panitia',
  path: '/panitia',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DesainRoute = DesainRouteImport.update({
  id: '/desain',
  path: '/desain',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desain': typeof DesainRoute
  '/gallery': typeof GalleryRoute
  '/panitia': typeof PanitiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desain': typeof DesainRoute
  '/gallery': typeof GalleryRoute
  '/panitia': typeof PanitiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/desain': typeof DesainRoute
  '/gallery': typeof GalleryRoute
  '/panitia': typeof PanitiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/desain' | '/gallery' | '/panitia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/desain' | '/gallery' | '/panitia'
  id: '__root__' | '/' | '/about' | '/desain' | '/gallery' | '/panitia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DesainRoute: typeof DesainRoute
  GalleryRoute: typeof GalleryRoute
  PanitiaRoute: typeof PanitiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panitia': {
      id: '/panitia'
      path: '/panitia'
      fullPath: '/panitia'
      preLoaderRoute: typeof PanitiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desain': {
      id: '/desain'
      path: '/desain'
      fullPath: '/desain'
      preLoaderRoute: typeof DesainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DesainRoute: DesainRoute,
  GalleryRoute: GalleryRoute,
  PanitiaRoute: PanitiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
